FROM python:3.7-alpine

MAINTAINER Pradeep Bashyal <pbashyal@nmdp.org>

RUN apk add --no-cache --virtual \
	.build-deps build-base gcc libc-dev \
	libxslt-dev libxslt \
	curl

RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir \
	html5lib==1.0.1 \
	lxml==4.4.1

RUN pip install --no-cache-dir \
	py-gfe==1.1.0 \
	py-ard==0.6.1

