FROM openjdk:8-alpine

MAINTAINER Pradeep Bashyal <pbashyal@nmdp.org>

ENV JAVA_HOME=usr/lib/jvm/java-1.8-openjdk

RUN apk add --no-cache --quiet curl wget perl gcc g++ make patch perl-dev

RUN curl -L http://xrl.us/cpanm > /bin/cpanm && chmod +x /bin/cpanm
RUN cpanm App::cpm
RUN cpanm install --force Bio::Perl

RUN apk add --no-cache python3 && \
        python3 -m ensurepip && \
        rm -r /usr/lib/python*/ensurepip && \
        pip3 install --upgrade pip setuptools && \
        if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && \
        if [[ ! -e /usr/bin/python ]]; then ln -sf /usr/bin/python3 /usr/bin/python; fi && \
        rm -r /root/.cache


RUN apk add --no-cache --quiet libxml2 libxslt libxml2-dev libxslt-dev
RUN apk add --no-cache python3-dev && \
    apk add --no-cache --virtual .build-deps g++ && \
    ln -s /usr/include/locale.h /usr/include/xlocale.h

RUN pip3 install html5lib==1.0.1 lxml==4.4.1

ENV PERL5LIB=/usr/local/lib/perl5

ARG NEO4J_URI=https://neo4j.com/artifact.php?name=neo4j-community-3.5.11-unix.tar.gz
ARG NEO4J_SHA256=4dd4f2b6c32e216b42ab8d2235f10c4d992d567d36927df93d2d9fb1763e6376
ARG NEO4J_TARBALL=neo4j-community.tar.gz

ENV NEO4J_CONF=/opt/conf
ENV NEO4J_BIN=/var/lib/neo4j/bin
ENV NEO4J_HOME=/var/lib/neo4j

RUN echo $NEO4J_URI
RUN echo $NEO4J_SHA256

RUN curl --fail --silent --show-error ${NEO4J_URI} -o ${NEO4J_TARBALL} && \
    echo "${NEO4J_SHA256}  ${NEO4J_TARBALL}" | sha256sum -cs && \
    tar --extract --file ${NEO4J_TARBALL} --directory /var/lib && \
    mv /var/lib/neo4j-community* /var/lib/neo4j && \
    rm ${NEO4J_TARBALL} && \
    echo Done!
