FROM openjdk:8-alpine

MAINTAINER Pradeep Bashyal <pbashyal@nmdp.org>

ENV JAVA_HOME=usr/lib/jvm/java-1.8-openjdk

RUN apk add --no-cache --quiet curl wget perl gcc g++ make patch perl-dev

RUN curl -L http://xrl.us/cpanm > /bin/cpanm && chmod +x /bin/cpanm
RUN cpanm App::cpm
RUN cpanm install --force Bio::Perl

RUN apk add --no-cache python3 && \
        python3 -m ensurepip && \
        rm -r /usr/lib/python*/ensurepip && \
        pip3 install --upgrade pip setuptools && \
        if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && \
        if [[ ! -e /usr/bin/python ]]; then ln -sf /usr/bin/python3 /usr/bin/python; fi && \
        rm -r /root/.cache


RUN apk add --no-cache --quiet libxml2 libxslt libxml2-dev libxslt-dev
RUN apk add --no-cache python3-dev && \
    apk add --no-cache --virtual .build-deps g++ && \
    ln -s /usr/include/locale.h /usr/include/xlocale.h

RUN pip3 install html5lib==1.0.1 lxml==4.1.1 numpy==1.13.3 pandas==0.21.1

RUN ENV PERL5LIB=/usr/local/lib/perl5
